--ozone-platform-hint=auto
--password-store=basic
--enable-features=WebUIDarkMode,GlobalMediaControls,NativeNotifications,AcceleratedVideoEncoder
--allow-insecure-localhost
--simulate-outdated-no-au=2099-12-31T23:59:59.00000Z
--force-dark-mode
